### ISSUE TITLE
Improve error responses

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#11]
Now any exeception raised in [BmiServer](https://github.com/eWaterCycle/grpc4bmi/blob/master/grpc4bmi/bmi_grpc_server.py) class will become a `StatusCode.UNKNOWN` grpc status code. 

There are more precise grpc status codes at https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
It would be nice if for example a NotImplementedError exception gets transformed into a UNIMPLEMENTED code.

**Comment by sverhoeven** [comment]
For R models a mapping based on the error message should be made, because R can only do `stop("my error message")`

**Comment by goord** [comment]
For C++ we should rely on exceptions, because it will mostly serve as an interface to e.g. fortran which doesn't issue exceptions. So I am using the BMI status codes (either fail or success) and map those to grpc status codes.

**Comment by sverhoeven** [comment]
Fixed in https://github.com/eWaterCycle/grpc4bmi/commit/60f36f2368f656631cf7cb0dd0b06320883b5db4
