### ISSUE TITLE
Rename master to main branch

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#125]

**Comment by BSchilperoort** [comment]
This one can be closed, right @sverhoeven ?

**Comment by sverhoeven** [comment]
Yep it can. 
Had to switch branch on 
1. readthedocs
2. CI workflow
3. sonarcloud, on sonarcloud.io needed to delete main branch and rename master 2 main then trigger a sonarcloud analysis

**Comment by BSchilperoort** [comment]
👍 

The readme does still seem to have one reference to master:
https://github.com/eWaterCycle/grpc4bmi/blob/ed59660999a64984dd600e45474ab666067c0b3a/README.md?plain=1#L74

However, github forwards you to main, so the link isn't broken.
