### ISSUE TITLE
Numpy integer array has dtype int64

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#15]
Add int64 to proto file.

**Comment by sverhoeven** [comment]
According to https://developers.google.com/protocol-buffers/docs/encoding#signed-integers every int is cast to a varint.

We should replace int32 by int64, then only casts from/to uint64 are problematic

**Comment by goord** [comment]
Fixed in cluster commit 48556c7ae04a6762a527c64d8a78ac60d268e98f
