### ISSUE TITLE
RemoteException: ValueError("did not find a match in any of xarray's currently installed IO backends 

### ISSUE THREAD

**Issue by Daafip** [eWaterCycle/grpc4bmi#151]
`RemoteException: ValueError("did not find a match in any of xarray's currently installed IO backends ['netcdf4']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:\nhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html\nhttps://docs.xarray.dev/en/stable/user-guide/io.html")`

Probably an issue due to my implementation of the BMI?

When is use:

```py
from grpc4bmi.bmi_client_docker import BmiClientDocker
model = BmiClientDocker(image='ghcr.io/daafip/hbv-bmi-grpc4bmi:v0.1.3', image_port=55555, work_dir='')
```

I can run `model.initialize('HBV_config.json')` which atleasts starts up fine.

Then trying to load in the model through pip install the 'proper way',  I get this error.

Any tips where/how to trouble shoot? Somewhere in the config then? 

BMI: https://github.com/Daafip/HBV-bmi
wrapper for eWaterCycle: https://github.com/Daafip/ewatercycle-hbv
last image: ghcr.io/daafip/hbv-bmi-grpc4bmi:v0.1.3

<details>
<summary>Error log</summary>
```py

---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_grpc_client.py:99, in BmiClient.initialize(self, filename)
     98 try:
---> 99     return self.stub.initialize(bmi_pb2.InitializeRequest(config_file=fname))
    100 except grpc.RpcError as e:

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc/_channel.py:1160, in _UnaryUnaryMultiCallable.__call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
   1154 (
   1155     state,
   1156     call,
   1157 ) = self._blocking(
   1158     request, timeout, metadata, credentials, wait_for_ready, compression
   1159 )
-> 1160 return _end_unary_response_blocking(state, call, False, None)

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc/_channel.py:1003, in _end_unary_response_blocking(state, call, with_call, deadline)
   1002 else:
-> 1003     raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "did not find a match in any of xarray's currently installed IO backends ['netcdf4']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-02-08T14:34:16.527522047+01:00", grpc_status:13, grpc_message:"did not find a match in any of xarray\'s currently installed IO backends [\'netcdf4\']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:\nhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html\nhttps://docs.xarray.dev/en/stable/user-guide/io.html"}"
>

The above exception was the direct cause of the following exception:

RemoteException                           Traceback (most recent call last)
Cell In[27], line 1
----> 1 model.initialize(config_file)

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/ewatercycle/base/model.py:168, in eWaterCycleModel.initialize(self, config_file)
    162 def initialize(self, config_file: str) -> None:
    163     """Initialize the model.
    164 
    165     Args:
    166         config_file: Name of initialization file.
    167     """
--> 168     self._bmi.initialize(config_file)

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_optionaldest.py:49, in OptionalDestBmi.initialize(self, config_file)
     48 def initialize(self, config_file: Optional[str]) -> None:
---> 49     return self.origin.initialize(config_file)

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_memoized.py:57, in MemoizedBmi.initialize(self, filename)
     55 def initialize(self, filename):
     56     self.cache = dict()
---> 57     return self.origin.initialize(filename)

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_grpc_client.py:101, in BmiClient.initialize(self, filename)
     99     return self.stub.initialize(bmi_pb2.InitializeRequest(config_file=fname))
    100 except grpc.RpcError as e:
--> 101     handle_error(e)

File ~/miniconda3/envs/ewatercycle/lib/python3.10/site-packages/grpc4bmi/bmi_grpc_client.py:46, in handle_error(exc)
     44         remote_traceback = info.stack_entries
     45         remote_detail = info.detail
---> 46         raise RemoteException(remote_detail, remote_traceback) from exc
     47 raise

RemoteException: ValueError("did not find a match in any of xarray's currently installed IO backends ['netcdf4']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:\nhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html\nhttps://docs.xarray.dev/en/stable/user-guide/io.html")

```
</details>

**Comment by BSchilperoort** [comment]
You need to include netcdf4 as a dependency in your containerized python environment. It is missing so the code is unable to open the netcdf file

**Comment by BSchilperoort** [comment]
Hm. It looks like you do have it. You can try to run the container interactively and attach a terminal to try to debug.

It could also be that you did not mount the drives correctly and that the model therefore cannot reach the netcdf file. Or the path in the config file is not absolute

**Comment by Daafip** [comment]
Thanks, I'll give that a try

**Comment by Daafip** [comment]
"Or the path in the config file is not absolute'' , yeah I thinks its this - i thought the forcing GenericLumpedForcing added the specified section to the path.
But you need to do this manually? or somewho specify it?

**Comment by Daafip** [comment]
When I specifically specify the full path to the forcing data by hand it does work
```py
config_file, _ = model.setup(
            precipitation_file=str(eWc_forcing_path / eWc_forcing_info['pr']),
            parameters=','.join([str(p) for p in par_0]),
            initial_storage=','.join([str(s) for s in s_0]),
           )
```

in [`demo_containerized_model.ipynb`](https://github.com/eWaterCycle/ewatercycle-leakybucket/blob/main/demo_containerized_model.ipynb) you dont do this? 

but maybe thats to do that its not on the eWaterCycle server but local? 

as i do load in: 

```py
rhine_forcing = GenericLumpedForcing(start_time = eWc_forcing_info['start_time'],
                     end_time = eWc_forcing_info['end_time'],
                     pr = eWc_forcing_info['pr'],
                     tas = eWc_forcing_info['tas'],
                     tasmin = eWc_forcing_info['tasmin'],
                     tasmax = eWc_forcing_info['tasmax'],
                     directory = eWc_forcing_path
                     )
```

and give that to the model

```py
image_link = "ghcr.io/daafip/hbv-bmi-grpc4bmi:v0.1.3"
from ewatercycle.container import ContainerImage
model = HBV(forcing=rhine_forcing, bmi_imag=ContainerImage(image_link))
```

**Comment by Daafip** [comment]
Edit: found where the difference is, need to specify that in the `_make_cfg_file()` of the `model.py` of the wrapper. 
Thanks!

**Comment by BSchilperoort** [comment]
In the first post you used the BmiClientDocker of grpc4bmi, this does not automatically mount the volumes of forcing/parameter sets. The ewatercycle ContainerizedModel will [add the forcing and parameterset paths automagically](https://github.com/eWaterCycle/ewatercycle/blob/d02450bb079d213f1c7f2ac0100268b0ad8cab1b/src/ewatercycle/base/model.py#L440-L451):

```py
    def _make_bmi_instance(self) -> bmipy.Bmi:
        if self.parameter_set:
            self._additional_input_dirs.append(str(self.parameter_set.directory))
        if self.forcing:
            self._additional_input_dirs.append(str(self.forcing.directory))

        return start_container(
            image=self.bmi_image,
            work_dir=self._cfg_dir,
            input_dirs=self._additional_input_dirs,
            timeout=300,
        )
```
These paths should already be made absolute by the Forcing and Parameterset classes.

> When I specifically specify the full path to the forcing data by hand it does work

In the leakybucket example the config file is generated in the LeakyBucketMethods class, it takes the (absolute) paths from the forcing and parameterset and creates a new config that is then used to initialize the model.

**Comment by BSchilperoort** [comment]
> found where the difference is, need to specify that in the `_make_cfg_file()` of the `model.py` of the wrapper.
> Thanks!

Good that you figured it out! I just finished typing up the explanation haha.

**Comment by Daafip** [comment]
"You can try to run the container interactively and attach a terminal to try to debug." -  can you explain how to do this?
Somewhat fixed the forcing issue but i still havinf some issues with `model.initialize()`

**Comment by BSchilperoort** [comment]
`docker run -it --entrypoint bash ghcr.io/ewatercycle/leakybucket-grpc4bmi:v0.0.1` will start the container, and give you interactive access to a (bash) terminal. This is mostly if you want to debug how the container works or check if things are set up correctly inside the container.

If you want to debug the BMI (and the issue is not related to the filesystem mounts), I'd advise [running a LocalModel](https://github.com/eWaterCycle/ewatercycle-leakybucket/blob/main/plugin_guide.md#local-python-model).

**Comment by Daafip** [comment]
Thanks, Have a LocalModel working now bug free, then launched a containerised version and that dit it too!
