### ISSUE TITLE
Change 50051 to 55555

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#24]
In the Docker images build we use 55555 .

**Comment by goord** [comment]
@sverhoeven how pressing is this? Should it be fixed before releasing?

**Comment by sverhoeven** [comment]
In https://github.com/eWaterCycle/experiment-launcher the 55555 port is specified so not needed for current release.

**Comment by sverhoeven** [comment]
Fixed in https://github.com/eWaterCycle/grpc4bmi/commit/0a432b17b38484513452c4090bade11fe944b8fb
