### ISSUE TITLE
In run-bmi-server allow --path to be specified as env var

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#28]
For run-bmi-server allow --path to be specified as env var like BMI_PATH. 

This would make it possible for the `BmiClientSingularity` to specify a port using command line args (run-bmi-server --port XXXX) and the model be configured using env vars.

**Comment by goord** [comment]
Fixed right in master with no tests: 49af7461ebcb64e1f593a943a0eab45895d44290
