### ISSUE TITLE
Add launch docker container flag to BmiDockerClient

### ISSUE THREAD

**Issue by goord** [eWaterCycle/grpc4bmi#36]
Sometimes people want to manually launch their docker container and connect to it using the docker client. This should be made possible with a flag.

**Comment by sverhoeven** [comment]
In that situation the only thing the docker client should do is destroy the container on exit. 
That seems not very useful. 

Is it not better to either let grpc4bmi manage the container completely (start and stop) or not manage it at all (use BmiClient)

**Comment by goord** [comment]
@sverhoeven agree this would make things unnecessarily complex
