### ISSUE TITLE
Support newest BMI standard

### ISSUE THREAD

**Issue by goord** [eWaterCycle/grpc4bmi#41]
The python BMI introduced destination array references: see https://bmi.readthedocs.io/en/latest/bmi.lang.py.html

We should 'emulate' support for this (destination array references are not very useful in an RPC bridge) by letting the BmiClient fill destination arrays whenever necessary.

**Comment by goord** [comment]
This version of the BMI is apparently not yet on PyPI so we will wait until it actually has been released...

**Comment by sverhoeven** [comment]
It is as [bmipy](https://pypi.org/project/bmipy/) of repo https://github.com/csdms/bmi-python

**Comment by sverhoeven** [comment]
The client should be update to the interface of bmipy.

The Python/R server should support the bmipy-1.0.0 and [basic-modeling-interface-0.2](https://pypi.org/project/basic-modeling-interface/). 
A flag (`--bmi-version 1.0.0|0.2`)  should be added in `run-bmi-server` to pick which interface is implemented by the model.

**Comment by goord** [comment]
Our C++ server should talk to the new methods in https://github.com/csdms/bmi/blob/master/bmi.h

**Comment by sverhoeven** [comment]
In test suite the walrus docker image is used. To update the docker image to the newest bmi interface:

1. https://github.com/eWaterCycle/bmi-r/blob/master/R/abstract-bmi.R must be branched + updated
2. https://github.com/eWaterCycle/grpc4bmi-examples/blob/master/walrus/ must be branched + updated
3. `ewatercycle/walrus-grpc4bmi:v0.3.0` Docker image must be created + pushed to docker hub
4. In grpc4bmi tests use version 0.3.0 of docker image.

**Comment by sverhoeven** [comment]
Reopen, https://github.com/eWaterCycle/bmi-r/blob/master/R/abstract-bmi.R and  https://github.com/eWaterCycle/grpc4bmi-examples/blob/master/walrus/ need to have their `newest-bmi-support` merged.

**Comment by sverhoeven** [comment]
Version 2.0 of [bmipy](https://pypi.org/project/bmipy/2.0/) and [bmi-cxx](https://github.com/csdms/bmi-cxx/releases/tag/v2.0) have been released.
Which add following functions:
* [ ] `get_grid_face_edges`
* [ ] `get_input_item_count`
* [ ] `get_output_item_count`
* [ ] `update_until` 

These methods should be added.

**Comment by sverhoeven** [comment]
All methods of bmipy v2.0 have been implemented in cpp, py client, py server.

Created https://github.com/eWaterCycle/grpc4bmi/issues/72 for ecosystem upgrade.
