### ISSUE TITLE
RSD adoption

### ISSUE THREAD

**Issue by goord** [eWaterCycle/grpc4bmi#42]
This software should get a citation file and an entry in the NLeSC RSD.

**Comment by sverhoeven** [comment]
Added citation file in b244598cd484f08a00f1abb8e0aaeb5e570003c8

**Comment by sverhoeven** [comment]
Created https://www.research-software.nl/admin/software/1f4f9428-7cff-459f-809e-bde0333ce08b, still needs further refining

**Comment by benvanwerkhoven** [comment]
The info on the RSD page looks ok to me, anyone mind if I push the 'is published?' button?

**Comment by sverhoeven** [comment]
Fine to publish by me

**Comment by goord** [comment]
Sure go ahead

**Comment by sverhoeven** [comment]
https://research-software.nl/software/grpc4bmi is online
