### ISSUE TITLE
c++ bindings not up to date

### ISSUE THREAD

**Issue by ipelupessy** [eWaterCycle/grpc4bmi#51]
I want to update hype-bmi to work again with newest grpc4bmi, however the current cpp BMI has moved again; it doesn't  makes sense to update the hype bmi to the current version used by grpc4bmi, does it? is there work in progress to update grpc4bmi?

**Comment by goord** [comment]
Euhm we had a request to make a release beginning of november, but maybe BMI-c++ has progressed further since then...

**Comment by ipelupessy** [comment]
it has, mainly its using c++ strings instead of char*

**Comment by goord** [comment]
Fixed in 0f5d8d495f2417825f99508428af02e946c10448
