### ISSUE TITLE
bmi_grpc_server.cc ignores BMI_PORT env var

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#55]
To configure the port the server is running on inside a container, the library uses the BMI_PORT environment variable. In the [construction of the server](https://github.com/eWaterCycle/grpc4bmi/blob/master/cpp/bmi_grpc_server.cc#L780-L785) only command line arguments and a default value are used to determine the port of the server.

Causes problems when running in Singularity container as it uses the network of the host so being unable to change the port makes it impossible to run multiple containers on the same host.

**Comment by sverhoeven** [comment]
The [Python based server](https://github.com/eWaterCycle/grpc4bmi/blob/master/grpc4bmi/run_server.py#L116-L118) ignores the env var when an `--port 12345` is given

**Comment by sverhoeven** [comment]
Also BmiClientDocker and BmiClientSingularity have no timeout to connect to the servers port so it will wait forever.

**Comment by goord** [comment]
I guess this issue has been resolved by pull request above and rev. cc4e057b449b4c764e34179e5cc07d51a92a8371
