### ISSUE TITLE
get_value resource exhausted

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/grpc4bmi#76]
For lisflood we have a global model with
```python
model.get_grid_shape(0)
(1500, 3600)
```

To get the discharge I use 

```python
model.get_value('Discharge')
```

which results in an error

```
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Received message larger than max (43200010 vs. 4194304)"
	debug_error_string = "{"created":"@1596101195.183981143","description":"Received message larger than max (43200010 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":174,"grpc_status":8}"
>
```

Using `get_value_at_indices` I am able to fetch 500k blocks anything more gives same error.

```python
model.get_value_at_indices('Discharge', np.array(range(500000,1000000)))
```

It would be nice if the `get_value()` and `get_value_at_indices()` had [streaming implementation](https://grpc.io/docs/languages/python/basics/#response-streaming-rpc) now I have to iterate (11x) myself.

**Comment by sverhoeven** [comment]
Or the library should handle the error more elagantly by for example catching the RESOURCE_EXHAUSTED error and falling back to reconstructing the value with get_value_at_indices calls by itself.

**Comment by goord** [comment]
Yes I think we should fall back to a streaming method if the message size is exceeded.

**Comment by sverhoeven** [comment]
The list flood model has a lot of nans adding [compression support](https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/doc/compression_cookbook.md) can give a intermediate fix.

**Comment by nielsdrost** [comment]
> The list flood model has a lot of nans adding [compression support](https://github.com/grpc/grpc/blob/master/doc/compression_cookbook.md) can give a intermediate fix. See https://grpc.github.io/grpc/python/grpc.html?highlight=compression#grpc.insecure_channel for Python client support.

I think this is probably the best option for now. Can you pass this option to grpc4bmi already in some way? Or do we need an update to grpc4bmi?

**Comment by sverhoeven** [comment]
Nevermind turning on compression results in same error:
```python
import grpc
from grpc4bmi.bmi_grpc_client import BmiClient
model = BmiClient(grpc.insecure_channel("localhost:55555", compression=grpc.Compression.Deflate))
from grpc4bmi.reserve import reserve_values
varname = model.get_output_var_names()[0]
client = model
client.get_value(varname, reserve_values(client, varname))
```

**Comment by sverhoeven** [comment]
To not have to rebuild the Docker images with grpc4bmi I will implement it client side only using indices to chunk the value.

**Comment by sverhoeven** [comment]
v0.2.8 and v0.3.1 have get_value which does chunking when needed.
